name = "sff-life"
account_id = ""
workers_dev = false
zone_id = ""
type = "javascript"
route = "sff.life/*"
compatibility_date = "2021-09-18"

[build]
command = "npm ci && hugo && cd workers-site && npm ci && npm run build"

[build.upload]
format = "service-worker"

[site]
bucket = "./public"
entry-point = "workers-site"
