name: ci
on:
  pull_request:
  push:
    branches:
    - master
  schedule:
  - cron: '00 01 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
      
    - name: Install hugo extended
      run: curl -L -o hugo.deb 'https://github.com/gohugoio/hugo/releases/download/v0.73.0/hugo_extended_0.73.0_Linux-64bit.deb' && sudo dpkg -i hugo.deb
   
    - name: Install wrangler
      run: npm i @cloudflare/wrangler -g
    
    - name: Hugo Build
      run: hugo
    
    - name: Wrangler Build
      run: wrangler build
